### PR TITLE
Closes #105 Fix bug on delete checklist request

### LINKED ISSUE #105: Fix bug on delete checklist request

### PR DESCRIPTION
**Pull request by anzhelikavelychko**

### CODE REVIEW

**Review by OBats — APPROVED** [review]

**Review by Yuri-Pristay — APPROVED** [review]

**Review by machikharostyk — APPROVED** [review]

**Review by romanolytvyn — APPROVED** [review]

File: api/models/user-model.js [hunk 1]
```diff
@@ -18,6 +18,10 @@ const userSchema = new mongoose.Schema({
     required: true,
     unique: true,
   },
+  creation_date: { 
+    type: Date, 
+    default: Date.now() 
+  },
   password: {
```
Comment (AndriyTykhan) [inline api/models/user-model.js]: { timestamp: true }

**Review by AndriyTykhan — APPROVED** [review]
